NoOptimization: mat_ops_Origonal.c 
	gcc -o NoOptimization mat_ops_Origonal.c
Opt_Ext_Lib: mat_ops_ExtLib.c
	gcc -o Opt_Ext_Lib mat_ops_ExtLib.c -lblas -lgfortran
Opt_Cache: mat_ops_OptCache.c
	gcc -o Opt_Cache mat_ops_OptCache.c 
Opt_Parallel: mat_ops_Parallel.c
	gcc -o Opt_Parallel mat_ops_Parallel.c
